import { Router } from 'express';
import {  addDoctor, DeleteDoctor, findAll, findOne ,UpdateDoctor} from '../controllers/Admin/DoctorFunctions.controller.js';
import { auth as _auth } from '../Middleware/user.auth.js';
import { validation } from './../Middleware/validation.js';
import { AddDoctorValidate, AddPharmacyValidate, UpdatePharmacyValidate } from './../validation/Admin.validation.js';
import { authorAdmin } from './../Middleware/author.js';
import { addPharmacist, DeletePharmacist, findAllPharmacist, findOnePharmacist, UpdatePharmacist } from '../controllers/Admin/PharmacistFunctional.controller.js';
const AdminRouter =Router();
AdminRouter.post('/AddDoctor',_auth,validation(AddDoctorValidate),authorAdmin,addDoctor);
AdminRouter.get('/findAll',_auth,authorAdmin,findAll);
AdminRouter.get('/findOneDoctor/:id',_auth,authorAdmin,findOne);
AdminRouter.put('/updateDoctor/:id',_auth,validation(AddDoctorValidate),authorAdmin,UpdateDoctor);
AdminRouter.delete('/DeleteDoctor/:id',_auth,authorAdmin,DeleteDoctor);
//////////////////////////////////////////
AdminRouter.post('/AddPharmacist',_auth,validation(AddPharmacyValidate),authorAdmin,addPharmacist);
AdminRouter.get('/findAllPharmacist',_auth,authorAdmin,findAllPharmacist);
AdminRouter.get('/findOnePharmacist/:id',_auth,authorAdmin,findOnePharmacist);
AdminRouter.put('/updatePharmacist/:id',_auth,validation(UpdatePharmacyValidate),authorAdmin,UpdatePharmacist);
AdminRouter.delete('/DeletePharmacist/:id',_auth,authorAdmin,DeletePharmacist);
export default AdminRouter;