import { Router } from 'express';
import {  addDoctor, DeleteDoctor, findAll, findOne ,UpdateDoctor} from '../controllers/Admin/DoctorFunctions.controller.js';
import { auth as _auth } from '../Middleware/user.auth.js';
import { validation } from './../Middleware/validation.js';
import { AddDoctorValidate } from './../validation/Admin.validation.js';
import { author } from './../Middleware/Admin.author.js';
const AdminRouter =Router();
// ProductRouter.get('/findUserAddBooks',_auth,findUserAddBooks);
AdminRouter.post('/AddDoctor',_auth,validation(AddDoctorValidate),author,addDoctor);
AdminRouter.get('/findAll',_auth,author,findAll);
AdminRouter.get('/findOneDoctor/:id',_auth,author,findOne);
AdminRouter.put('/updateDoctor/:id',_auth,validation(AddDoctorValidate),author,UpdateDoctor);
AdminRouter.delete('/Delete/:id',_auth,author,DeleteDoctor);
export default AdminRouter;